# Generated by Django 5.1.5 on 2025-01-24 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkpostlikemanager',
            old_name='user',
            new_name='liked_by',
        ),
        migrations.AlterUniqueTogether(
            name='networkpostlikemanager',
            unique_together={('liked_by', 'post')},
        ),
    ]
